<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit788fd2f8f3ec3dc8a99dd34fe13eaef3
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Wechat\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Wechat\\' => 
        array (
            0 => __DIR__ . '/..' . '/zoujingli/wechat-php-sdk/Wechat',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit788fd2f8f3ec3dc8a99dd34fe13eaef3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit788fd2f8f3ec3dc8a99dd34fe13eaef3::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
